# Generated by Django 5.0.6 on 2024-06-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('group', models.UUIDField()),
            ],
        ),
    ]
