# Generated by Django 5.0.6 on 2024-06-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
