# Generated by Django 5.0.6 on 2024-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_plans', '0002_event_creator_event_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
