# Generated by Django 5.1.7 on 2025-03-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_alter_event_id_alter_group_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events_going', to='calendarapp.user'),
        ),
    ]
